#!/bin/bash
#
# This script builds and installs MJIN2 dependencies for Windows.
#
# REQUIREMENTS
#
# 1. Run it only after installing MinGW, Cygwin, CMake under Windows.
# 2. Rename Cygwin's sh.exe to sh_.exe, otherwise CMake refuses to work.
#

SRC_DIR=$1
BUILD_DIR=$2
if [ -z $SRC_DIR ] || [ -z $BUILD_DIR ]; then
    echo "Usage: $0 SRC_DIR BUILD_DIR"
    exit
fi
CWD=`pwd`
MINGW_DIR="C:/MinGW"
# Get Unix names for Unix utils.
SRC_DIRU=`cygpath $SRC_DIR`
BUILD_DIRU=`cygpath $BUILD_DIR`
# Versions.
LIBPNG_VERSION=1.6.1
LIBXML2_VERSION=2.9.0
ZLIB_VERSION=1.2.7

# libxml2. 
cd $CWD
LIBXML2=$BUILD_DIRU/libxml2
if [ ! -d $LIBXML2 ]; then
    echo "libxml2 is not found. Building it."
    mkdir -p $LIBXML2
    tar -xf $SRC_DIRU/libxml2-$LIBXML2_VERSION.tar.gz -C $LIBXML2
    cd $LIBXML2/libxml2-$LIBXML2_VERSION/win32
    cscript configure.js prefix=C:\\MinGW compiler=mingw iconv=no
    make
    make install
    strip -s $MINGW_DIR/bin/libxml2.dll
else
    echo "libxml2 was found in '$LIBXML2'. Skipping."
fi

# zlib.
cd $CWD
ZLIB=$BUILD_DIRU/zlib
if [ ! -d $ZLIB ]; then
    echo "zlib is not found. Building it."
    mkdir -p $ZLIB/{src,build}
    tar -xf $SRC_DIRU/zlib-$ZLIB_VERSION.tar.bz2 -C $ZLIB/src
    # CMake complains about the file, so remove it.
    rm $ZLIB/src/zlib-$ZLIB_VERSION/zconf.h
    cd $ZLIB/build
    cmake -G "MinGW Makefiles" \
          -DCMAKE_INSTALL_PREFIX=$MINGW_DIR \
          ../src/zlib-$ZLIB_VERSION
    make
    # Fix bug for OGRE. Not sure if it's necessary for OSG. Keep it for now.
    #sed -i 's/MOVEABLE IMPURE LOADONCALL DISCARDABLE//' $ZLIB/src/zlib-$ZLIB_VERSION/win32/zlib1.rc
    make install
else
    echo "zlib was found in '$ZLIB'. Skipping."
fi

# libpng. 
cd $CWD
LIBPNG=$BUILD_DIRU/libpng
if [ ! -d $LIBPNG ]; then
    echo "libpng is not found. Building it."
    mkdir -p $LIBPNG/{src,build}
    tar -xf $SRC_DIRU/libpng-$LIBPNG_VERSION.tar.xz -C $LIBPNG/src
    cd $LIBPNG/build
    cmake -G "MinGW Makefiles" \
          -DCMAKE_INSTALL_PREFIX=$MINGW_DIR \
          ../src/libpng-$LIBPNG_VERSION
    make
    make install
else
    echo "libpng was found in '$LIBPNG'. Skipping."
fi

