# -*- coding: utf-8 -*-

text = """
msgid $Eng$
msgstr "$Ger$"
"""

keyField = 'Eng'

marker = '$'

extension = 'txt'

prefix = 'de_'

parts = {
         }

cutLastSymb = ['data']

oneFile = True

header = """# Generated by script"""

footer = """"""

replacement = {
               }