#!/usr/bin/python
# -*- coding: utf-8 -*-

'''
Shuan gameplay slice prototype mission root module

(c) 2010 Opensource Game Studio Team (http://opengamestudio.org)
'''

from Enemies import Enemy1, Enemy2, Enemy3, Enemy22, Boss1, Boss2
from Effects import BossMessage

from .Core.MissionTemplate import MissionTemplate

class Mission(MissionTemplate):
    '''
    Shuan gameplay slice prototype mission root class
    '''
    name = 'Simple Mission'
    speed = 2
    landTexture = 'mars'
    
    boss = None
    bossMeter = None
    
    music = 'Dirty_Road_Blues'
    
    sequence = (
                ('Wait',50),
                ('Spawn', Enemy1, 50),
                ('Spawn', Enemy2, 40),
                ('Spawn', Enemy1, 30),
                ('Wait',20),
                ('Spawn', Enemy1, 60),
                ('Spawn', Enemy2, 70),
                ('Spawn', Enemy1, 80),
                ('Wait',20),
                ('Spawn', Enemy1, 50),
                ('Spawn', Enemy2, 40),
                ('Spawn', Enemy1, 30),
                ('Wait',50),
                ('Spawn', Enemy1, 10),
                ('Wait',2),
                ('Spawn', Enemy1, 20),
                ('Wait',2),
                ('Spawn', Enemy1, 30),
                ('Wait',2),
                ('Spawn', Enemy1, 40),
                ('Wait',2),
                ('Spawn', Enemy1, 50),
                ('Wait',20),
                ('Spawn', Enemy1, 90),
                ('Wait',2),
                ('Spawn', Enemy1, 80),
                ('Wait',2),
                ('Spawn', Enemy1, 70),
                ('Wait',2),
                ('Spawn', Enemy1, 60),
                ('Wait',2),
                ('Spawn', Enemy1, 50),
                ('Wait',50),
                ('Spawn', Enemy3, 50),
                ('Spawn', Enemy3, 45),
                ('Spawn', Enemy3, 55),
                ('Spawn', Enemy3, 40),
                ('Spawn', Enemy3, 60),
                ('Spawn', Enemy1, 70),
                ('Spawn', Enemy1, 30),
                ('Wait',30),
                ('Spawn', Enemy2, 40),
                ('Wait',10),
                ('Spawn', Enemy2, 60),
                ('Wait',10),
                ('Spawn', Enemy2, 40),
                ('Wait',10),
                ('Spawn', Enemy2, 60),
                ('Wait',10),
                ('Spawn', Enemy2, 40),
                ('Wait',10),
                ('Spawn', Enemy2, 60),
                ('Wait',10),
                ('Spawn', Enemy2, 40),
                ('Wait',10),
                ('Spawn', Enemy2, 60),
                ('Wait',30),
                ('Spawn', Enemy1, 50),
                ('Spawn', Enemy2, 40),
                ('Spawn', Enemy1, 30),
                ('Wait',15),
                ('Spawn', Enemy1, 60),
                ('Spawn', Enemy2, 70),
                ('Spawn', Enemy1, 80),
                ('Wait',15),
                ('Spawn', Enemy1, 50),
                ('Spawn', Enemy2, 40),
                ('Spawn', Enemy1, 30),
                ('Spawn', Enemy2, 20),
                ('Wait',15),
                ('Spawn', Enemy1, 60),
                ('Spawn', Enemy2, 70),
                ('Spawn', Enemy1, 80),
                ('Spawn', Enemy2, 20),
                ('Wait',15),
                ('Spawn', Enemy1, 50),
                ('Wait',7),
                ('Spawn', Enemy2, 40),
                ('Wait',7),
                ('Spawn', Enemy1, 30),
                ('Wait',7),
                ('Spawn', Enemy2, 20),
                ('Wait',15),
                ('Spawn', Enemy1, 60),
                ('Wait',7),
                ('Spawn', Enemy2, 70),
                ('Wait',7),
                ('Spawn', Enemy1, 80),
                ('Wait',7),
                ('Spawn', Enemy2, 20),
                ('Wait',40),
                ('Speed',1),
                ('Wait',30),
                ('Boss', Boss1),
                ('Wait',30),
                ('Speed',0),
                ('WaitBossKill',),
                ('Wait',10),
                ('Speed',1),
                ('Wait',30),
                ('Speed',2),
                ('Wait',50),
                ('Spawn', Enemy3, 45),
                ('Spawn', Enemy3, 55),
                ('Spawn', Enemy3, 40),
                ('Spawn', Enemy3, 60),
                ('Spawn', Enemy22, 35),
                ('Spawn', Enemy22, 65),
                ('Spawn', Enemy2, 70),
                ('Spawn', Enemy2, 30),
                ('Wait',20),
                ('Spawn', Enemy2, 70),
                ('Spawn', Enemy2, 30),
                ('Wait',7),
                ('Spawn', Enemy22, 50),
                ('Wait',7),
                ('Spawn', Enemy2, 40),
                ('Wait',7),
                ('Spawn', Enemy1, 30),
                ('Wait',7),
                ('Spawn', Enemy2, 20),
                ('Wait',15),
                ('Spawn', Enemy1, 60),
                ('Wait',7),
                ('Spawn', Enemy2, 70),
                ('Wait',7),
                ('Spawn', Enemy1, 80),
                ('Wait',7),
                ('Spawn', Enemy2, 20),
                ('Wait',30),
                ('Spawn', Enemy2, 40),
                ('Wait',10),
                ('Spawn', Enemy2, 60),
                ('Wait',10),
                ('Spawn', Enemy2, 40),
                ('Wait',10),
                ('Spawn', Enemy2, 60),
                ('Wait',10),
                ('Spawn', Enemy2, 40),
                ('Wait',10),
                ('Spawn', Enemy2, 60),
                ('Wait',10),
                ('Spawn', Enemy2, 40),
                ('Wait',10),
                ('Spawn', Enemy2, 60),
                ('Wait',15),
                ('Spawn', Enemy1, 50),
                ('Spawn', Enemy2, 40),
                ('Spawn', Enemy1, 30),
                ('Spawn', Enemy22, 20),
                ('Wait',15),
                ('Spawn', Enemy1, 60),
                ('Spawn', Enemy2, 70),
                ('Spawn', Enemy1, 80),
                ('Spawn', Enemy22, 90),
                ('Wait',30),
                ('Spawn', Enemy1, 50),
                ('Spawn', Enemy2, 40),
                ('Spawn', Enemy1, 30),
                ('Wait',15),
                ('Spawn', Enemy1, 60),
                ('Spawn', Enemy2, 70),
                ('Spawn', Enemy1, 80),
                ('Wait',15),
                ('Spawn', Enemy1, 50),
                ('Spawn', Enemy2, 40),
                ('Spawn', Enemy1, 30),
                ('Spawn', Enemy22, 20),
                ('Wait',15),
                ('Spawn', Enemy1, 60),
                ('Spawn', Enemy2, 70),
                ('Spawn', Enemy1, 80),
                ('Spawn', Enemy22, 90),
                ('Wait',40),
                ('Speed',1),
                ('Wait',30),
                ('Boss', Boss2),
                ('Wait',30),
                ('Speed',0),
                ('WaitBossKill',),
                )