#!/usr/bin/perl
# Update PO.
use strict;
use warnings;

my ($txt, $po) = @ARGV;
unless ($txt && $po) {
    print "Usage: $0 TXT PO > new.po\n\n",
          "TXT - Input plain text file with English strings\n",
          "PO  - Output PO file to update with missing strings, ",
          "or warn of outdated strings\n\n",
          "$0 will print new.po with MISSING keyword in case of missing translation\n";
    exit;
}
my $fh;
open($fh, $txt);
my %txtLines;
for my $ln (<$fh>) {
    chomp($ln);
    $txtLines{$ln} = 1 unless ($ln =~ /^#/ || !$ln);
}
close($fh);
open($fh, $po);
my @poLns = <$fh>;
close($fh);
my $msgid  = 0;
my $msgstr = 0;
my %poLines;
for my $ln (@poLns) {
    if ($ln =~ /msgid \"(.+?)\"\n/) {
        $poLines{$msgid} = $msgstr if ($msgid && $msgid ne $1);
        $msgid = $1;
        $msgstr = 0;
    }
    elsif ($ln =~ /msgstr \"(.+?)\"\n/) {
        $msgstr = $1;
    }
}
$poLines{$msgid} = $msgstr if ($msgid);
for my $ln (sort keys %txtLines) {
    if (exists $poLines{$ln} && $poLines{$ln}) {
        print "msgid \"$ln\"\nmsgstr \"" . $poLines{$ln} . "\"\n\n";
    }
    else {
        print "msgid \"$ln\"\nmsgstr \"MISSING\"\n\n";
    }
}

